version: "3.9"

services:
  postgres:
    container_name: medical_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medicalService
    volumes:
      - medical_service_data:/var/lib/postgresql/data
    networks:
      - medical_service

volumes:
  medical_service_data:
    name: medical_service_data

networks:
  medical_service:
    driver: bridge