spring:
  application:
    name: medicalService
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
        instanceId: ${spring.application.name}:${random.value}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
      auto-startup: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      acks: 1
      spring:
        json:
          add:
            type:
              headers: false
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
kafka:
  topic:
    vaccineQrTopicName: vaccine_qr_generation_topic

scheduler:
  refresh-patient-info-job-cron: 0 0 2 * * ?