server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/medicalService
    username: postgres
    password: postgres
  flyway:
    enabled: true

app:
  secret: some-secret-key2