CREATE TABLE VACCINATION_PLACE(
    ID INT PRIMARY KEY,
    ORGANIZATION_NAME VARCHAR,
    DIVISION_NAME VARCHAR
);

CREATE TABLE VACCINE_TYPE(
    CODE VARCHAR PRIMARY KEY,
    DESCRIPTION VARCHAR,
    DURATION_IN_DAYS INT
);

CREATE TABLE VACCINE(
    ID BIGINT PRIMARY KEY,
    VACCINATION_DATE DATE,
    VACCINE_TYPE_CODE VARCHAR REFERENCES VACCINE_TYPE(CODE),
    VACCINATION_PLACE_ID INT REFERENCES VACCINATION_PLACE(ID),
    CITIZEN_ID BIGINT
);

CREATE SEQUENCE VACCINE_SEQ increment 1 start 1;
CREATE SEQUENCE VACCINATION_PLACE_SEQ increment 1 start 1;

INSERT INTO VACCINE_TYPE
VALUES ('SPUTNIK_V', 'Спутник V»', 365);
INSERT INTO VACCINE_TYPE
VALUES ('SPUTNIK_LIGHT', 'Спутник Лайт»', 183);
INSERT INTO VACCINE_TYPE
VALUES ('EPI_VAC_CORONA', 'ЭпиВакКорона»', 183);
INSERT INTO VACCINE_TYPE
VALUES ('COVI_VAC', 'КовиВак»', 243);
INSERT INTO VACCINE_TYPE
VALUES ('PFIZER', 'Pfizer/BioNTech', 365);
INSERT INTO VACCINE_TYPE
VALUES ('MODERNA', 'Moderna', 365);
INSERT INTO VACCINE_TYPE
VALUES ('ASTRA_ZENECA', 'AstraZeneca', 365);
INSERT INTO VACCINE_TYPE
VALUES ('SINOPHARM', 'Sinopharm', 243);
INSERT INTO VACCINE_TYPE
VALUES ('SINOVAC', 'Sinovac', 243);