CREATE TABLE PATIENT (
    ID BIGINT PRIMARY KEY,
    CITIZEN_ID BIGINT,
    FIRST_NAME varchar,
    SECOND_NAME varchar,
    PASSPORT_NUMBER varchar
);

ALTER TABLE vaccine ADD COLUMN PATIENT_ID BIGINT REFERENCES PATIENT(ID);

ALTER TABLE vaccine DROP COLUMN citizen_id;

CREATE SEQUENCE PATIENT_SEQ increment 1 start 1;